[project]
name = "systematicreview-agridata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fitz",
    "google-genai",
    "openpyxl",
    "pandas",
    "python-dotenv",
    "xlrd"
]
